- search_page.html
Added new serach page with search bar
> Added Search Page

- favorites_page.html
- index.html
- item_page.html
- search_page.html
- seller_page.html
Added header links to other pages.
Added header on item page
> Added Header Links

- assets/css/main.css
- latest_page.html
> Add Latest page

- favorites_page.html
- latest_page.html
Pages other that the homepage should not have a popup (shown to yu on the HP) so I removed/ hide it on the following pages
> Hide pop up on pages

- favorites_page.html
- index.html
- item_page.html
- latest_page.html
- search_page.html
- seller_page.html
Added link to the logo, so when you click on it, it takes you back to the home page.
Related issue:
https://github.com/e-manLV/yrdzl/issues/19
> Added link to logo

- results.html
related Issue:
https://github.com/e-manLV/yrdzl/issues/16
> Create search results images

- search_results.html
Updated search bar/button.
Linked button to search results page
Created Funko Pop search results page
Related issue(s):
https://github.com/e-manLV/yrdzl/issues/18
> Updated Search/Search Results

- assets/css/main.css
Updated color on dropdown menu
Related ticket:
https://github.com/e-manLV/yrdzl/issues/45
> Update dropdown menu

- assets/css/main.css
- search_page.html
- search_results.html
Added content header
Centered search bar
Centered search term on results page
Issue:
https://github.com/e-manLV/yrdzl/issues/51
> Update search page

- yardz.html
Removed pop-up
Issue:
https://github.com/e-manLV/yrdzl/issues/44
> Removed popup on yardz

- assets/css/main.css
- results.html
Centered search bar and search term.
Issues:
https://github.com/e-manLV/yrdzl/issues/59
> Updated seller search bar

- latest_page.html
- search_page.html
Added search bar
Issue:
https://github.com/e-manLV/yrdzl/issues/43
> Add search bar

- assets/css/main.css
Updated font family, size and added outline.
Issue:
https://github.com/e-manLV/yrdzl/issues/63
> Updated font

- results.html
- seller_page.html
Replaced some of the funko pop pics on seller_page
Issue:
https://github.com/e-manLV/yrdzl/issues/49
> Replaced pics

- assets/css/main.css
- results.html
- seller_page.html
Updated user seller image and name
Related issue:
https://github.com/e-manLV/yrdzl/issues/58
> Updated User

- favorites_page.html
- item_page2.html
- latest_page.html
- seller_page.html
adding 2nd item page and updating photos/links in favs/latest/seller pages to point to 2nd page.
> adding 2nd item page

- favorites_page.html
- seller_page.html
Updated fav page to reflect the images with hearts
Updated seller page: removed some of the pics to make it seem that not all hearted items came from this seller.
Related issues:
https://github.com/e-manLV/yrdzl/issues/60
> Updated Fav img

- assets/css/main.css
- search_page.html
- yardz.html
Resized the logo so that it wasn't being cut off
Updated footer content on search and yardz to match other pages
Related issue:
https://github.com/e-manLV/yrdzl/issues/72
> Updated Logo size

- item_page.html
- item_page2.html
Added shipping form to item pages
> Added Shipping form

- assets/css/main.css
- item_page.html
- item_page2.html
-updating font color
-moving descriptions
-adding top padding
> item page updates
